### ISSUE TITLE
remove spell

### ISSUE THREAD

**Issue by erel3** [donpiekarz/spellbook#4]
how to remove spells or spellbooks?

**Comment by donpiekarz** [comment]
All spellbooks are located in: $HOME/.spellbook/ 
There you can just delete the file with spellbook or direcly edit it with some text editor. The syntax inside is simple json. One spell per line. You will see :)

**Comment by maxwellgerber** [comment]
I've noticed that $HOME/.spellbook/blah is a text file with a new JSON object on each line, instead of being a single JSON object. So the flow is (text file)> open as text file> process each line as its own JSON> process each JSON object as a python dict. This means that there's many hoops to jump through whenever you try to do something, like deleting a spell from a spellbook. I think it would be much cleaner if it was something like (json object file)> process with JSON> iterate through JSON object. I forked the project and am trying to implement a rm function.

**Comment by donpiekarz** [comment]
Reason for not have list of dicts is to not load whole file at once. And it is easier to manually edit file.

**Comment by maxwellgerber** [comment]
I don't see why loading the entire file at once would be a problem.
We also wouldn't need to manually edit the file if we had a rm command.
Currently the rm command I have implemented searches through the file in the same way search_spell() does and lets users tag the command they wish to remove.
My issue is that I don't see a simple way to keep track of which spells have been deleted. If a user deletes a spell locally, and then syncs with the dropbox repo, then how do we prevent the spell from appearing again? Should we just allow this?

**Comment by donpiekarz** [comment]
Idea behind not loading whole file at once is to faster produce some output. Now I want to be compatible with all previous versions. We could try do some perf tests and if it is fine then implement some function to convert spellbooks to new format.

When revision of local spellbook is same as remote, then upload is without conflicts (the chagnes in that spellbook are not important). 
When revision is different, then spellbook is adding remote spells to local spellbook. So yes, it is possible to add again that spell, but this use case is very rare. It is better to add spell again then lose it.

**Comment by rnelson0** [comment]
That assumes the spell is valid. Perhaps it is removed because it is actually incorrect.

Maybe add an option to sync to 'push' or 'override' the remote side, or 'newest'/'oldest' to choose the winner.

**Comment by donpiekarz** [comment]
That's right :)

Feel free to pull request!
